{
  logsForTarget: [
    {
      MessageTemplate: 'Receive message {IncomingMessageType} {IncomingMessageId}.',
      Level: 'Information',
      Properties: {
        IncomingMessage: {
          TypeTag: 'StartHandlerThatLogs'
        },
        OriginatingHostId: Guid_1,
        MessageIntent: 'Send',
        OriginatingEndpoint: 'SerilogTestsStartHandlerThatLogs',
        OriginatingMachine: 'TheMachineName',
        ReplyToAddress: 'SerilogTestsStartHandlerThatLogs',
        TimeSent: DateTime_1,
        IncomingMessageId: Guid_2,
        IncomingMessageType: 'StartHandlerThatLogs',
        CorrelationId: Guid_2,
        ConversationId: Guid_3,
        SourceContext: 'StartHandlerThatLogs',
        ProcessingEndpoint: 'SerilogTestsStartHandlerThatLogs'
      }
    },
    {
      MessageTemplate: 'Sent message {OutgoingMessageType} {OutgoingMessageId}.',
      Level: 'Information',
      Properties: {
        OutgoingMessage: {
          TypeTag: 'StartHandlerThatLogs'
        },
        UnicastRoutes: {
          Elements: [
            'SerilogTestsStartHandlerThatLogs'
          ]
        },
        OriginatingHostId: Guid_1,
        MessageIntent: 'Send',
        OriginatingEndpoint: 'SerilogTestsStartHandlerThatLogs',
        OriginatingMachine: 'TheMachineName',
        ReplyToAddress: 'SerilogTestsStartHandlerThatLogs',
        OutgoingMessageId: Guid_2,
        OutgoingMessageType: 'StartHandlerThatLogs',
        CorrelationId: Guid_2,
        ConversationId: Guid_3,
        SourceContext: 'StartHandlerThatLogs',
        ProcessingEndpoint: 'SerilogTestsStartHandlerThatLogs'
      }
    }
  ],
  logsWithExceptions: [
    {
      MessageTemplate: 'Immediate Retry is going to retry message \'00000000-0000-0000-0000-000000000001\' because of an exception:',
      Level: 'Information',
      Properties: {
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_4,
        ProcessingEndpoint: 'SerilogTestsNotFoundSagaMessage',
        CorrelationId: Guid_2,
        ConversationId: Guid_5,
        IncomingMessage: {
          TypeTag: 'NotFoundSagaMessage',
          Properties: [
            {
              Property: null
            }
          ]
        },
        IncomingHeaders: {
          Elements: {
            "NServiceBus.SagaId": Guid_6,
            "NServiceBus.SagaType": 'TheSaga',
            "NServiceBus.MessageId": Guid_2,
            "NServiceBus.MessageIntent": 'Send',
            "NServiceBus.ConversationId": Guid_5,
            "NServiceBus.CorrelationId": Guid_2,
            "NServiceBus.ReplyToAddress": 'SerilogTestsNotFoundSagaMessage',
            "NServiceBus.OriginatingMachine": 'TheMachineName',
            "NServiceBus.OriginatingEndpoint": 'SerilogTestsNotFoundSagaMessage',
            "$.diagnostics.originating.hostid": Guid_1,
            "NServiceBus.ContentType": 'text/xml',
            "NServiceBus.EnclosedMessageTypes": 'NotFoundSagaMessage, Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce8ec7717ba6fbb6',
            "NServiceBus.Version": 'NsbVersion',
            "NServiceBus.TimeSent": DateTime_2
          }
        },
        SourceContext: 'NServiceBus.RecoverabilityExecutor',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.NullReferenceException',
            "HResult": -2147467261,
            "Message": 'Object reference not set to an instance of an object.',
            "Source": 'NServiceBus.Core'
          }
        }
      }
    },
    {
      MessageTemplate: 'Delayed Retry will reschedule message \'00000000-0000-0000-0000-000000000001\' after a delay of 00:00:00.0010000 because of an exception:',
      Level: 'Warning',
      Properties: {
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_4,
        ProcessingEndpoint: 'SerilogTestsNotFoundSagaMessage',
        CorrelationId: Guid_2,
        ConversationId: Guid_5,
        IncomingMessage: {
          TypeTag: 'NotFoundSagaMessage',
          Properties: [
            {
              Property: null
            }
          ]
        },
        IncomingHeaders: {
          Elements: {
            "NServiceBus.SagaId": Guid_6,
            "NServiceBus.SagaType": 'TheSaga',
            "NServiceBus.MessageId": Guid_2,
            "NServiceBus.MessageIntent": 'Send',
            "NServiceBus.ConversationId": Guid_5,
            "NServiceBus.CorrelationId": Guid_2,
            "NServiceBus.ReplyToAddress": 'SerilogTestsNotFoundSagaMessage',
            "NServiceBus.OriginatingMachine": 'TheMachineName',
            "NServiceBus.OriginatingEndpoint": 'SerilogTestsNotFoundSagaMessage',
            "$.diagnostics.originating.hostid": Guid_1,
            "NServiceBus.ContentType": 'text/xml',
            "NServiceBus.EnclosedMessageTypes": 'NotFoundSagaMessage, Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce8ec7717ba6fbb6',
            "NServiceBus.Version": 'NsbVersion',
            "NServiceBus.TimeSent": DateTime_2
          }
        },
        SourceContext: 'NServiceBus.RecoverabilityExecutor',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.NullReferenceException',
            "HResult": -2147467261,
            "Message": 'Object reference not set to an instance of an object.',
            "Source": 'NServiceBus.Core'
          }
        }
      }
    },
    {
      MessageTemplate: 'Immediate Retry is going to retry message \'00000000-0000-0000-0000-000000000001\' because of an exception:',
      Level: 'Information',
      Properties: {
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_7,
        ProcessingEndpoint: 'SerilogTestsNotFoundSagaMessage',
        CorrelationId: Guid_2,
        ConversationId: Guid_5,
        IncomingMessage: {
          TypeTag: 'NotFoundSagaMessage',
          Properties: [
            {
              Property: null
            }
          ]
        },
        IncomingHeaders: {
          Elements: {
            "NServiceBus.SagaId": Guid_6,
            "NServiceBus.SagaType": 'TheSaga',
            "NServiceBus.MessageId": Guid_2,
            "NServiceBus.MessageIntent": 'Send',
            "NServiceBus.ConversationId": Guid_5,
            "NServiceBus.CorrelationId": Guid_2,
            "NServiceBus.ReplyToAddress": 'SerilogTestsNotFoundSagaMessage',
            "NServiceBus.OriginatingMachine": 'TheMachineName',
            "NServiceBus.OriginatingEndpoint": 'SerilogTestsNotFoundSagaMessage',
            "$.diagnostics.originating.hostid": Guid_1,
            "NServiceBus.ContentType": 'text/xml',
            "NServiceBus.EnclosedMessageTypes": 'NotFoundSagaMessage, Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce8ec7717ba6fbb6',
            "NServiceBus.Version": 'NsbVersion',
            "NServiceBus.TimeSent": DateTime_2,
            "NServiceBus.Retries": '1',
            "NServiceBus.Retries.Timestamp": DateTime_3
          }
        },
        SourceContext: 'NServiceBus.RecoverabilityExecutor',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.NullReferenceException',
            "HResult": -2147467261,
            "Message": 'Object reference not set to an instance of an object.',
            "Source": 'NServiceBus.Core'
          }
        }
      }
    },
    {
      MessageTemplate: 'Moving message \'00000000-0000-0000-0000-000000000001\' to the error queue \'error\' because processing failed due to an exception:',
      Level: 'Error',
      Properties: {
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_7,
        ProcessingEndpoint: 'SerilogTestsNotFoundSagaMessage',
        CorrelationId: Guid_2,
        ConversationId: Guid_5,
        IncomingMessage: {
          TypeTag: 'NotFoundSagaMessage',
          Properties: [
            {
              Property: null
            }
          ]
        },
        IncomingHeaders: {
          Elements: {
            "NServiceBus.SagaId": Guid_6,
            "NServiceBus.SagaType": 'TheSaga',
            "NServiceBus.MessageId": Guid_2,
            "NServiceBus.MessageIntent": 'Send',
            "NServiceBus.ConversationId": Guid_5,
            "NServiceBus.CorrelationId": Guid_2,
            "NServiceBus.ReplyToAddress": 'SerilogTestsNotFoundSagaMessage',
            "NServiceBus.OriginatingMachine": 'TheMachineName',
            "NServiceBus.OriginatingEndpoint": 'SerilogTestsNotFoundSagaMessage',
            "$.diagnostics.originating.hostid": Guid_1,
            "NServiceBus.ContentType": 'text/xml',
            "NServiceBus.EnclosedMessageTypes": 'NotFoundSagaMessage, Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce8ec7717ba6fbb6',
            "NServiceBus.Version": 'NsbVersion',
            "NServiceBus.TimeSent": DateTime_2,
            "NServiceBus.Retries": '1',
            "NServiceBus.Retries.Timestamp": DateTime_3
          }
        },
        SourceContext: 'NServiceBus.RecoverabilityExecutor',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.NullReferenceException',
            "HResult": -2147467261,
            "Message": 'Object reference not set to an instance of an object.',
            "Source": 'NServiceBus.Core'
          }
        }
      }
    },
    {
      MessageTemplate: 'The message',
      Level: 'Error',
      Properties: {
        SourceContext: 'TheHandlerThatThrows',
        ExceptionDetail: {
          Elements: {
            "Type": 'System.Exception',
            "HResult": -2146233088,
            "Message": 'Exception of type \'System.Exception\' was thrown.',
            "Source": null
          }
        }
      }
    }
  ]
}